### PR TITLE
Lilac protype working with a driver  and CTSM.

### PR DESCRIPTION
**Pull request by negin513**
This is the initial prototype of lilac which works with a demo_driver (stand-alone driver) and CTSM lilac cap. The demo_driver functions as our "dummy" atmosphere.

### CODE REVIEW

**Comment by jhamman** [comment]
Where would I find the version of CTSM that includes `lnd_comp_esmf`?

**Comment by jhamman** [comment]
I spent some time getting started on this today. Here's a quick update:

1. I'm pointing to https://github.com/mvertens/ctsm.git@mvertens/lilac for our CTSM build. Is this the right branch?
2. We should probably discuss pushing some of the build improvements upstream to CIME and CTSM. It should be possible to build both libraries outside of a CIME Case. It would be nice if LILAC didn't have to maintain build infrastructure for both of these repos. AFAICT, `CIME_initial_setup` is created during setup of a case and this is baked into all of the CIME/CTSM CMAKE build scripts. I could probably use some help from @billsacks on this one.
3. Dependencies - what should we assume is available in the user environment and what should lilac vendor? My working assumption is as follows:
    - Dependencies - Fortran90+ compiler , C++ compiler, MPI, NetCDF4, Cmake
    - Vendor: ESMF, CIME, CTSM

**Comment by billsacks** [comment]
@jhamman - I think @negin513 can answer some of the questions from your last post, including (2), but if not, I'm happy to try to help. A quick clarification: currently, the CMake scripts in CTSM are not at all tied in to a case, but rather are used in the unit test build. I think `CIME_initial_setup` can be skipped for the sake of the LILAC build, but I could easily be missing something (I think @negin513 understands this better than I do).

**Comment by jhamman** [comment]
> I think CIME_initial_setup can be skipped for the sake of the LILAC build

AFAICT, the cmake build scripts for both CIME and CTSM error if `CIME_initial_setup` has not be set. I also see that @negin513 has worked on this so I'll check with her.

**Comment by negin513** [comment]
> 2. We should probably discuss pushing some of the build improvements upstream to CIME and CTSM. It should be possible to build both libraries outside of a CIME Case. It would be nice if LILAC didn't have to maintain build infrastructure for both of these repos. AFAICT, `CIME_initial_setup` is created during setup of a case and this is baked into all of the CIME/CTSM CMAKE build scripts. I could probably use some help from @billsacks on this one.

Agreed with pushing some of the build improvements upstream to CIME and CTSM. 
Lilac CMake should be used both for building Lilac and unit-testing. Hence, I think Lilac build should be tied to a case, and we need the `CIME_initial_setup`. @billsacks  Please correct me on this, if I am wrong.

**Comment by billsacks** [comment]
For Lilac, we won't in general have a case, in the sense of a typical cime case.

**Comment by jhamman** [comment]
@negin513 and I spoke today about the status of things. We came up with the following plan:

1. strive to keep the LILAC build as simple as possible, ask upstream libraries (CTSM, CIME) to maintain a slightly more flexible version of their current CMake infrastructure.
2. help CTSM/CIME implement changes to meet the needs of 3rd parties that simply want to link to their library
3. if this seems to be impossible, write our own CMake build script for both CTSM and CIME. This of course is likely to be more expensive up front and more brittle in the long run.

I've opened two issues in the CIME and CTSM repos to discuss some improvements to the CMake builds upstream. @billsacks, it would be great if you can look over these when you get a minute.

xref: https://github.com/ESCOMP/ctsm/issues/799, https://github.com/ESMCI/cime/issues/3226

**Comment by billsacks** [comment]
@negin513 @mvertens I suggest merging these changes to master, then merging in @mvertens 's recent changes on top of these. Do you agree?

**Pull request merged**
